services:
  - type: web
    name: whatsapp-server
    env: docker
    region: singapore # Closest to India
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: ALLOWED_ORIGINS
        sync: false # This will be set manually in Render dashboard
      - key: PUPPETEER_ARGS
        value: "--no-sandbox --disable-setuid-sandbox"
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    dockerfilePath: ./Dockerfile # Specify root-level Dockerfile
    # Additional Docker settings for Chrome in container
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
